import { PermissionsBitField } from 'discord.js';
import type { Client, Guild, GuildMember } from 'discord.js';
import type { ApiClient, ModerationActionJob } from './api-client.js';

export class ModerationActionRunner {constructor(private readonly client:Client,private readonly api:ApiClient,private readonly botId:string){}
 async runPending():Promise<void>{const actions=await this.api.moderationActions(this.botId);for(const action of actions)await this.run(action);}
 private async run(action:ModerationActionJob):Promise<void>{try{const guild=this.client.guilds.cache.get(action.guild_discord_id)??await this.client.guilds.fetch(action.guild_discord_id);const member=await guild.members.fetch(action.target_user_discord_id);await this.ensureActionAllowed(guild,member,action);if(action.type==='disconnect'){await member.voice.disconnect(action.reason??undefined);await this.api.updateModerationAction(action.id,{result:'success'});return;}if(action.type==='timeout'){await member.timeout((action.duration_seconds??600)*1000,action.reason??undefined);await this.api.updateModerationAction(action.id,{result:'success'});return;}if(action.type==='warn'){await member.send(`Avertissement de modération vocale : ${action.reason??'aucun motif précisé'}`).catch(()=>undefined);await this.api.updateModerationAction(action.id,{result:'success'});return;}await this.api.updateModerationAction(action.id,{result:'recorded'});}catch(error){await this.api.updateModerationAction(action.id,{result:'failed',error_message:error instanceof Error?error.message:'Erreur inconnue'});}}
 private async ensureActionAllowed(guild:Guild,member:GuildMember,action:ModerationActionJob):Promise<void>{const botMember=guild.members.me??await guild.members.fetchMe();if(member.id===guild.ownerId)throw new Error('Impossible de sanctionner le propriétaire du serveur.');if(member.id===botMember.id)throw new Error('Le bot ne peut pas se sanctionner lui-même.');if(action.type==='warn')return;if(action.type==='disconnect'){if(!botMember.permissions.has(PermissionsBitField.Flags.MoveMembers))throw new Error('Permission Discord manquante : Déplacer des membres.');if(!member.voice.channelId)throw new Error('Utilisateur introuvable dans un salon vocal.');this.ensureRoleHierarchy(botMember,member);return;}if(action.type==='timeout'){if(!botMember.permissions.has(PermissionsBitField.Flags.ModerateMembers))throw new Error('Permission Discord manquante : Modérer les membres.');if(!member.moderatable)throw new Error('Utilisateur non modérable par ce bot. Vérifie la hiérarchie des rôles Discord.');this.ensureRoleHierarchy(botMember,member);}}
 private ensureRoleHierarchy(botMember:GuildMember,member:GuildMember):void{if(member.roles.highest.comparePositionTo(botMember.roles.highest)>=0)throw new Error('Utilisateur au même niveau ou au-dessus du bot dans la hiérarchie des rôles Discord.');}
}
