<?php
namespace App\Filament\Resources;
use App\Filament\Resources\ModerationActionResource\Pages; use App\Models\ModerationAction; use Filament\Forms; use Filament\Forms\Form; use Filament\Resources\Resource; use Filament\Tables; use Filament\Tables\Table; use Illuminate\Database\Eloquent\Builder;
class ModerationActionResource extends Resource { protected static ?string $model=ModerationAction::class; protected static ?string $navigationIcon='heroicon-o-shield-check'; protected static ?string $navigationLabel='Actions de modération'; protected static ?string $navigationGroup='Modération';
 public static function canViewAny(): bool{return auth()->user()?->canApplySanctions() ?? false;}
 public static function canCreate(): bool{return auth()->user()?->canApplySanctions() ?? false;}
 public static function canEdit($record): bool{return auth()->user()?->canApplySanctions() ?? false;}
 public static function canDelete($record): bool{return auth()->user()?->isSuperAdmin() ?? false;}
 public static function form(Form $form): Form{return $form->schema([Forms\Components\Section::make('Action')->columns(2)->schema([Forms\Components\Select::make('voice_report_id')->label('Signalement')->relationship('report','reason')->searchable()->preload(),Forms\Components\Select::make('discord_guild_id')->label('Serveur')->relationship('guild','name')->required()->searchable()->preload(),Forms\Components\TextInput::make('moderator_discord_id')->label('Modérateur'),Forms\Components\TextInput::make('target_user_discord_id')->label('Utilisateur concerné')->required(),Forms\Components\Select::make('type')->label('Type')->options(['warn'=>'Avertissement','disconnect'=>'Déconnexion vocale','move'=>'Déplacement','mute'=>'Mute serveur','timeout'=>'Timeout','kick'=>'Expulsion','ban'=>'Bannissement','note'=>'Note','dismiss'=>'Classement sans suite','delete_audio'=>'Suppression audio'])->required(),Forms\Components\TextInput::make('duration_seconds')->label('Durée en secondes')->numeric(),Forms\Components\Select::make('result')->label('Résultat')->options(['pending'=>'En attente','recorded'=>'Enregistré','success'=>'Succès','failed'=>'Échec'])->default('recorded')->required(),Forms\Components\DateTimePicker::make('actioned_at')->label('Action le')->default(now()),Forms\Components\Textarea::make('reason')->label('Motif')->columnSpanFull(),Forms\Components\Textarea::make('error_message')->label('Erreur')->columnSpanFull()])]);}
 public static function table(Table $table): Table{return $table->modifyQueryUsing(fn(Builder $query)=>$query->latest('actioned_at'))->defaultSort('actioned_at','desc')->poll('10s')->columns([Tables\Columns\TextColumn::make('actioned_at')->label('Action le')->dateTime()->sortable(),Tables\Columns\TextColumn::make('type')->label('Type')->formatStateUsing(fn(string $state):string=>match($state){'warn'=>'Avertissement','disconnect'=>'Déconnexion vocale','move'=>'Déplacement','mute'=>'Mute serveur','timeout'=>'Timeout','kick'=>'Expulsion','ban'=>'Bannissement','note'=>'Note','dismiss'=>'Classement sans suite','delete_audio'=>'Suppression audio',default=>$state})->badge(),Tables\Columns\TextColumn::make('guild.name')->label('Serveur')->searchable(),Tables\Columns\TextColumn::make('target_user_discord_id')->label('Utilisateur')->formatStateUsing(fn($state,ModerationAction $record):string=>\App\Models\DiscordMember::query()->where('discord_guild_id',$record->discord_guild_id)->where('discord_id',$state)->value('display_name') ?: $state)->description(fn(ModerationAction $record):string=>$record->target_user_discord_id)->copyable()->searchable(),Tables\Columns\TextColumn::make('result')->label('Résultat')->formatStateUsing(fn(string $state):string=>match($state){'pending'=>'En attente','recorded'=>'Enregistré','success'=>'Succès','failed'=>'Échec',default=>$state})->badge()->color(fn(string $state):string=>match($state){'success','recorded'=>'success','failed'=>'danger','pending'=>'warning',default=>'gray'}),Tables\Columns\TextColumn::make('error_message')->label('Erreur')->limit(60)->toggleable(),Tables\Columns\TextColumn::make('reason')->label('Motif')->limit(50)])->actions([Tables\Actions\Action::make('retry')->label('Réessayer')->icon('heroicon-o-arrow-path')->visible(fn(ModerationAction $record):bool=>$record->result==='failed')->action(fn(ModerationAction $record)=>$record->update(['result'=>'pending','error_message'=>null])),Tables\Actions\EditAction::make()])->bulkActions([Tables\Actions\BulkAction::make('retrySelected')->label('Réessayer la sélection')->icon('heroicon-o-arrow-path')->action(fn($records)=>$records->each->update(['result'=>'pending','error_message'=>null])),Tables\Actions\DeleteBulkAction::make()->label('Supprimer la sélection')]);}
 public static function getPages():array{return ['index'=>Pages\ListModerationActions::route('/'),'create'=>Pages\CreateModerationAction::route('/create'),'edit'=>Pages\EditModerationAction::route('/{record}/edit')];}}
