<?php
namespace App\Filament\Resources;
use App\Filament\Resources\VoiceSessionResource\Pages; use App\Filament\Resources\VoiceSessionResource\RelationManagers; use App\Models\VoiceSession; use Filament\Forms; use Filament\Forms\Form; use Filament\Resources\Resource; use Filament\Tables; use Filament\Tables\Table; use Illuminate\Database\Eloquent\Builder;
class VoiceSessionResource extends Resource { protected static ?string $model=VoiceSession::class; protected static ?string $navigationIcon='heroicon-o-signal'; protected static ?string $navigationLabel='Sessions vocales'; protected static ?string $navigationGroup='Modération'; protected static bool $shouldRegisterNavigation=false;
 public static function form(Form $form): Form{return $form->schema([Forms\Components\Section::make('Session')->columns(2)->schema([Forms\Components\Select::make('discord_bot_id')->label('Bot')->relationship('bot','name')->disabled(),Forms\Components\Select::make('discord_guild_id')->label('Serveur')->relationship('guild','name')->disabled(),Forms\Components\Select::make('discord_channel_id')->label('Salon')->relationship('channel','name')->disabled(),Forms\Components\TextInput::make('status')->disabled(),Forms\Components\TextInput::make('member_count')->label('Membres')->disabled(),Forms\Components\DateTimePicker::make('started_at')->disabled(),Forms\Components\DateTimePicker::make('last_activity_at')->disabled(),Forms\Components\DateTimePicker::make('ended_at')->disabled(),Forms\Components\Textarea::make('error_message')->columnSpanFull()->disabled()])]);}
 public static function table(Table $table): Table{return $table->modifyQueryUsing(fn(Builder $query)=>$query->latest('started_at'))->poll('5s')->columns([Tables\Columns\TextColumn::make('status')->label('Statut')->formatStateUsing(fn(string $state):string=>match($state){'active'=>'Active','empty'=>'Vide','error'=>'Erreur','ended'=>'Terminée',default=>$state})->badge()->color(fn(string $state):string=>match($state){'active'=>'success','empty'=>'warning','error'=>'danger','ended'=>'gray',default=>'info'})->sortable(),Tables\Columns\TextColumn::make('bot.name')->label('Bot')->searchable(),Tables\Columns\TextColumn::make('guild.name')->label('Serveur')->searchable(),Tables\Columns\TextColumn::make('channel.name')->label('Salon')->searchable(),Tables\Columns\TextColumn::make('member_count')->label('Membres')->sortable(),Tables\Columns\TextColumn::make('started_at')->label('Début')->dateTime()->sortable(),Tables\Columns\TextColumn::make('last_activity_at')->label('Dernière activité')->dateTime()->since(),Tables\Columns\TextColumn::make('ended_at')->label('Fin')->dateTime()->toggleable(isToggledHiddenByDefault:true),Tables\Columns\TextColumn::make('error_message')->label('Erreur')->limit(40)->toggleable(isToggledHiddenByDefault:true)])->filters([Tables\Filters\SelectFilter::make('status')->label('Statut')->options(['active'=>'Active','empty'=>'Vide','error'=>'Erreur','ended'=>'Terminée']),Tables\Filters\Filter::make('active')->label('Actives')->query(fn(Builder $query)=>$query->whereNull('ended_at'))])->actions([Tables\Actions\EditAction::make()->label('Voir'),Tables\Actions\Action::make('end')->label('Terminer')->icon('heroicon-o-stop-circle')->color('danger')->requiresConfirmation()->visible(fn(VoiceSession $record):bool=>$record->ended_at===null)->action(fn(VoiceSession $record)=>$record->update(['status'=>'ended','ended_at'=>now(),'last_activity_at'=>now()])),Tables\Actions\DeleteAction::make()->label('Supprimer')])->bulkActions([Tables\Actions\DeleteBulkAction::make()->label('Supprimer la sélection')]);}
 public static function canCreate(): bool{return false;}
 public static function getRelations(): array{return [RelationManagers\MembersRelationManager::class];}
 public static function getPages():array{return ['index'=>Pages\ListVoiceSessions::route('/'),'edit'=>Pages\EditVoiceSession::route('/{record}/edit')];}}
