<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::table('discord_guilds',function(Blueprint $t){$t->string('moderator_role_discord_id')->nullable()->after('is_active');$t->string('log_channel_discord_id')->nullable()->after('moderator_role_discord_id');$t->string('report_channel_discord_id')->nullable()->after('log_channel_discord_id');});
 Schema::create('discord_members',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('discord_guild_id')->constrained()->cascadeOnDelete();$t->string('discord_id');$t->string('display_name');$t->text('avatar')->nullable();$t->boolean('is_owner')->default(false)->index();$t->timestampsTz();$t->unique(['discord_guild_id','discord_id']);});
 Schema::create('discord_roles',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('discord_guild_id')->constrained()->cascadeOnDelete();$t->string('discord_id');$t->string('name');$t->unsignedInteger('position')->default(0);$t->boolean('is_moderator')->default(false)->index();$t->timestampsTz();$t->unique(['discord_guild_id','discord_id']);});
 Schema::create('bot_guild_assignments',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('discord_bot_id')->constrained()->cascadeOnDelete();$t->foreignUuid('discord_guild_id')->constrained()->cascadeOnDelete();$t->boolean('is_active')->default(true)->index();$t->jsonb('config')->default('{}');$t->timestampsTz();$t->unique(['discord_bot_id','discord_guild_id']);});
 Schema::create('voice_channel_assignments',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('discord_channel_id')->constrained()->cascadeOnDelete();$t->foreignUuid('discord_bot_id')->constrained()->cascadeOnDelete();$t->boolean('is_active')->default(true)->index();$t->unsignedSmallInteger('buffer_seconds')->default(45);$t->boolean('volume_analysis_enabled')->default(false);$t->boolean('transcription_enabled')->default(false);$t->unsignedSmallInteger('retention_days')->default(30);$t->jsonb('moderation_config')->default('{}');$t->timestampsTz();$t->unique('discord_channel_id');});
 Schema::create('voice_sessions',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('discord_bot_id')->constrained()->cascadeOnDelete();$t->foreignUuid('discord_guild_id')->constrained()->cascadeOnDelete();$t->foreignUuid('discord_channel_id')->constrained()->cascadeOnDelete();$t->string('status')->default('starting')->index();$t->timestampTz('started_at');$t->timestampTz('ended_at')->nullable();$t->timestampTz('last_activity_at')->nullable();$t->unsignedSmallInteger('member_count')->default(0);$t->text('error_message')->nullable();$t->timestampsTz();});
 Schema::create('voice_session_members',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('voice_session_id')->constrained()->cascadeOnDelete();$t->string('discord_user_id');$t->string('display_name')->nullable();$t->timestampTz('joined_at');$t->timestampTz('left_at')->nullable();$t->timestampsTz();$t->unique(['voice_session_id','discord_user_id']);});
 Schema::create('voice_events',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('discord_guild_id')->nullable()->constrained()->nullOnDelete();$t->foreignUuid('discord_channel_id')->nullable()->constrained()->nullOnDelete();$t->string('discord_user_id')->nullable()->index();$t->string('type')->index();$t->jsonb('payload')->default('{}');$t->timestampTz('occurred_at')->index();$t->timestampsTz();});
 Schema::create('voice_reports',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('discord_guild_id')->constrained()->cascadeOnDelete();$t->foreignUuid('discord_channel_id')->constrained()->cascadeOnDelete();$t->foreignUuid('voice_session_id')->nullable()->constrained()->nullOnDelete();$t->string('reported_user_discord_id')->index();$t->string('reporter_user_discord_id')->index();$t->string('reason');$t->text('comment')->nullable();$t->string('status')->default('pending')->index();$t->timestampTz('reported_at')->index();$t->timestampsTz();$t->softDeletesTz();});
 Schema::create('moderation_actions',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('voice_report_id')->nullable()->constrained()->nullOnDelete();$t->foreignUuid('discord_guild_id')->constrained()->cascadeOnDelete();$t->string('moderator_discord_id')->nullable()->index();$t->string('target_user_discord_id')->index();$t->string('type')->index();$t->unsignedInteger('duration_seconds')->nullable();$t->text('reason')->nullable();$t->string('result')->default('pending')->index();$t->text('error_message')->nullable();$t->timestampTz('actioned_at')->nullable();$t->timestampsTz();});
 Schema::create('system_logs',function(Blueprint $t){$t->uuid('id')->primary();$t->string('level')->default('info')->index();$t->string('source')->index();$t->string('event')->index();$t->text('message');$t->jsonb('context')->default('{}');$t->timestampTz('occurred_at')->index();$t->timestampsTz();});
 } public function down(): void {Schema::dropIfExists('system_logs');Schema::dropIfExists('moderation_actions');Schema::dropIfExists('voice_reports');Schema::dropIfExists('voice_events');Schema::dropIfExists('voice_session_members');Schema::dropIfExists('voice_sessions');Schema::dropIfExists('voice_channel_assignments');Schema::dropIfExists('bot_guild_assignments');Schema::dropIfExists('discord_roles');Schema::dropIfExists('discord_members');Schema::table('discord_guilds',function(Blueprint $t){$t->dropColumn(['moderator_role_discord_id','log_channel_discord_id','report_channel_discord_id']);});} };
