<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller; use App\Models\VoiceSession; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request;
class VoiceSessionController extends Controller {
 public function store(Request $request): JsonResponse { $data=$this->validated($request); $session=VoiceSession::query()->create([...collect($data)->except('members')->all(),'status'=>'active','started_at'=>now(),'last_activity_at'=>now()]); $this->syncMembers($session,$data['members']??[]); return response()->json(['data'=>['id'=>$session->id,'status'=>$session->status]],201); }
 public function heartbeat(Request $request, VoiceSession $voiceSession): JsonResponse { $data=$request->validate(['member_count'=>'required|integer|min:0|max:65535','status'=>'nullable|in:active,empty,error','members'=>'array','members.*.discord_user_id'=>'required|string|max:255','members.*.display_name'=>'nullable|string|max:255']); $voiceSession->update(['member_count'=>$data['member_count'],'status'=>$data['status']??$voiceSession->status,'last_activity_at'=>now()]); $this->syncMembers($voiceSession,$data['members']??[]); return response()->json(['data'=>['accepted'=>true]]); }
 public function destroy(VoiceSession $voiceSession): JsonResponse { $voiceSession->update(['status'=>'ended','ended_at'=>now(),'last_activity_at'=>now()]); return response()->json(['data'=>['accepted'=>true]]); }
 private function validated(Request $request): array {return $request->validate(['discord_bot_id'=>'required|exists:discord_bots,id','discord_guild_id'=>'required|exists:discord_guilds,id','discord_channel_id'=>'required|exists:discord_channels,id','member_count'=>'integer|min:0|max:65535','members'=>'array','members.*.discord_user_id'=>'required|string|max:255','members.*.display_name'=>'nullable|string|max:255']);}
 private function syncMembers(VoiceSession $session,array $members): void { $seen=[]; foreach($members as $member){$seen[]=$member['discord_user_id'];$session->members()->updateOrCreate(['discord_user_id'=>$member['discord_user_id']],['display_name'=>$member['display_name']??null,'joined_at'=>now(),'left_at'=>null]);} if($seen!==[]){$session->members()->whereNotIn('discord_user_id',$seen)->whereNull('left_at')->update(['left_at'=>now()]);} }
}
